spring:
  application:
    name: main-server

  config:
    import:
      application-secret.yml

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org.hibernate.type: trace

baseUrl: http://localhost:8080

server:
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
