spring:
  application:
    name: main-server

  config:
    import:
      application-secret.yml

  jpa:
    properties:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.hibernate.type: trace

baseUrl: http://localhost:8080
