spring:
  application:
    name: main-server

  config:
    import:
      application-secret.yml

  jpa:
    hibernate:
      ddl-auto: create

  data:
    redis:
      host: localhost
      port: 6379

  logging:
    level:
      root: trace