spring:
  application:
    name: main-server

  config:
    import:
      application-secret.yml

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

    data:
      redis:
        host: localhost
        port: 6379

logging:
  level:
    org.hibernate.type: trace
